# docker-compose.yml
version: '3.8'
services:
  db:
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: worldss
    healthcheck:
      test: "mysqladmin ping --silent"
      interval: 10s
      timeout: 5s
      retries: 5
