name: Java CI/CD with Docker SQL

on:
  push:
    branches:
      - master
      - release
      - develop
  pull_request:
    branches:
      - master
      - release
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:8
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_DATABASE: your_database_name
        options: --health-cmd "mysqladmin ping --silent" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Install docker-compose
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Start Docker SQL Container
        run: |
          docker-compose up -d

      - name: Install dependencies
        run: mvn install -DskipTests

      - name: Run Tests
        run: mvn test

      - name: Build the project
        run: mvn package

      - name: Stop Docker SQL Container
        run: |
          docker-compose down
