name: Testing for the application
on: push

jobs:
  build:
    name: Setting Up Build Enviroment
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Unit Tests For Menu
        run: mvn -Dtest=group8.UnitTestingMenu test
      - name: Integration Tests For Database
        run: mvn -Dtest=group8.integrationtests test
      - name: Package and Run docker compose
        run: |
          mvn package -DskipTests
          docker compose up --abort-on-container-exit

